# Generated by Django 4.1.2 on 2024-07-14 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0002_remove_venta_descuento_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Jornada',
            new_name='Tipo_moneda',
        ),
        migrations.RenameField(
            model_name='contacto',
            old_name='nombres',
            new_name='nombre_completo',
        ),
        migrations.RenameField(
            model_name='contacto',
            old_name='jornada',
            new_name='tipo_moneda',
        ),
        migrations.RenameField(
            model_name='tipo_moneda',
            old_name='id_jornada',
            new_name='id_tipo_moneda',
        ),
        migrations.RenameField(
            model_name='tipo_moneda',
            old_name='nombre_jornada',
            new_name='tipo_moneda',
        ),
        migrations.RemoveField(
            model_name='contacto',
            name='apellido_materno',
        ),
        migrations.RemoveField(
            model_name='contacto',
            name='apellido_paterno',
        ),
        migrations.RemoveField(
            model_name='contacto',
            name='comentarios',
        ),
        migrations.RemoveField(
            model_name='contacto',
            name='curriculum',
        ),
        migrations.RemoveField(
            model_name='contacto',
            name='rut',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='descripcion',
        ),
        migrations.AddField(
            model_name='producto',
            name='is_oferta',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='producto',
            name='precio_oferta',
            field=models.IntegerField(null=True),
        ),
    ]
