# Generated by Django 4.1.2 on 2024-07-15 21:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0003_rename_jornada_tipo_moneda_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Compra_producto',
            fields=[
                ('id_compra', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField(null=True)),
                ('monto_total', models.IntegerField(null=True)),
                ('id_producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productos.producto')),
            ],
        ),
    ]
